/**
 * Auto-generated list of Atlas Images
 * Generated on: 2025-12-08T02:22:06.432Z
 * Total images: 484
 */

export const ATLAS_IMAGES = [
  "CATARACT_\"Y-suture\"-Cataract.jpg",
  "CATARACT_Aftercataract-Elschnigs-pearls.jpg",
  "CATARACT_Anterior-capsular-phimosis.jpg",
  "CATARACT_Anterior-chamber-intraocular-lens-ACIOL-implant.jpg",
  "CATARACT_Anterior-polar-cataract.jpg",
  "CATARACT_Anterior-subcapsular-cataract.jpg",
  "CATARACT_Artisanclaw-intraocular-lens.jpg",
  "CATARACT_Bilateral-posterior-polar-cataracts.jpg",
  "CATARACT_Brunescent-cataract,-mature.jpg",
  "CATARACT_Brunescent-cataract.jpg",
  "CATARACT_Calcific-Deposits-on-an-Intraocular-Lens.jpg",
  "CATARACT_Capsular-folds-secondary-to-posterior-capsule-opacification.jpg",
  "CATARACT_Capsular-violation.jpg",
  "CATARACT_Cataract-with-cortical-vacuoles.jpg",
  "CATARACT_Cataract-with-refractile-bodies.jpg",
  "CATARACT_Cerulean-Cataract.jpg",
  "CATARACT_Chlorpromazine-induced-cataract.jpg",
  "CATARACT_Clear-crystalline-lens.jpg",
  "CATARACT_Combined-Anterior-Polar,-Posterior-Subcapsular-and-Cortical-Cataract.jpg",
  "CATARACT_Congenital-Cataract,-Sutural.jpg",
  "CATARACT_Congenital-lamellar-zonular-cataract-in-a-child.jpg",
  "CATARACT_Congenital-nuclear-cataract.jpg",
  "CATARACT_Coppock-Cataract.jpg",
  "CATARACT_Decentered-posterior-chamber-intraocular-lens.jpg",
  "CATARACT_Delayed-postoperative-fungal-endophthalmitis.jpg",
  "CATARACT_Epicapsular-stars-and-persistent-pupillary-membrane.jpg",
  "CATARACT_Glaukomflecken-and-iris-atrophy-after-acute-angle-closure-glaucoma.jpg",
  "CATARACT_Hyphema-following-aborted-iStent-procedure.jpg",
  "CATARACT_Iridodialysis-and-traumatic-cataract-after-firecracker-injury.jpg",
  "CATARACT_Iris-coloboma.jpg",
  "CATARACT_Iris-incarceration-in-an-old-extracapsular-wound.jpg",
  "CATARACT_Kayser-Fleischer-Ring-in-Wilsons-Disease.jpg",
  "CATARACT_Late-Capsular-Block-with-Posterior-Capsular-Fibrosis.jpg",
  "CATARACT_Layered-intracapsular-hemorrhage-following-phacoemulsification-GATT.jpg",
  "CATARACT_Marfans-Syndrome.jpg",
  "CATARACT_Mature-Cataract.jpg",
  "CATARACT_Mature-cortical-cataract.jpg",
  "CATARACT_Mittendorf-dot.jpg",
  "CATARACT_Morgagnian-cataract-with-absent-cortex.jpg",
  "CATARACT_Morgagnian-cataract.jpg",
  "CATARACT_Nuclear-sclerotic-cataract.jpg",
  "CATARACT_Ocular-Syphilis-Presenting-with-Posterior-Subcapsular-Cataract.jpg",
  "CATARACT_Oil-droplet-cataract.jpg",
  "CATARACT_Ointment-in-anterior-chamber-after-cataract-surgery.jpg",
  "CATARACT_Opacification-of-Hydrophilic-Intraocular-Lens.jpg",
  "CATARACT_Persistent-Pupillary-Membrane-2.jpg",
  "CATARACT_Persistent-fetal-vasculature-PFV.jpg",
  "CATARACT_Persistent-pupillary-membranes-1.jpg",
  "CATARACT_Phacomorphic-Angle-Closure-and-Anterior-Lens-Dislocation-due-to-Repeated-Blunt-Trauma.jpg",
  "CATARACT_Posterior-Polar-Cataract-with-Traumatic-Posterior-Capsule-Rupture.jpg",
  "CATARACT_Posterior-Polar-Cataract.jpg",
  "CATARACT_Posterior-capsular-opacity-PCO-following-cataract-surgery.jpg",
  "CATARACT_Posterior-subcapsular-cataract--retroillumination.jpg",
  "CATARACT_Posterior-subcapsular-cataract.jpg",
  "CATARACT_Pseudoexfoliation-syndrome.jpg",
  "CATARACT_Pseudoexfoliation-zonular-dehiscence.jpg",
  "CATARACT_Retained-Lens-Fragment.jpg",
  "CATARACT_Siderosis-bulbi.jpg",
  "CATARACT_Silicone-oil-droplet-on-intraocular-lens-IOL.jpg",
  "CATARACT_Subluxated-posterior-chamber-intraocular-lens-implant.jpg",
  "CATARACT_Temporal-iris-and-lens-coloboma-associated-with-cataract.jpg",
  "CATARACT_Traumatic-aniridia-and-cataract.jpg",
  "CATARACT_Traumatic-rosette-cataract.jpg",
  "CATARACT_Unique-Electric-Cataract.jpg",
  "CATARACT_Vitreous-strand-to-paracentesis-causing-subtle-peaked-pupil-early-in-case.jpg",
  "CATARACT_White-cataract-from-trauma.jpg",
  "CATARACT_Zonules-of-Zinn.jpg",
  "CONTACT LENS_Anterior-capsular-phimosis.jpg",
  "CONTACT LENS_Appropriate-Scleral-Lens-Sagittal-Depth.jpg",
  "CONTACT LENS_Congenital-nuclear-cataract.jpg",
  "CONTACT LENS_EyePrint-Pro®-over-mini-penetrating-keratoplasty-PKP.jpg",
  "CONTACT LENS_Lens-Fluting.jpg",
  "CONTACT LENS_Lipid-Deposits-on-Scleral-Rigid-Gas-Permeable-RGP-Lens.jpg",
  "CONTACT LENS_Orthokeratology.jpg",
  "CONTACT LENS_Scratched-Scleral-Rigid-Gas-Permeable-RGP-Lens.jpg",
  "CONTACT LENS_Surface-Coating-Loss-on-Scleral-Lens.jpg",
  "CORNEA_Acanthamoeba-keratitis.jpg",
  "CORNEA_Anterior-chamber-intraocular-lens-ACIOL-implant.jpg",
  "CORNEA_Arcus-senilis.jpg",
  "CORNEA_Avellino-dystrophy.jpg",
  "CORNEA_Band-keratopathy.jpg",
  "CORNEA_Blepharitis.jpg",
  "CORNEA_Conjunctival-lymphoma.jpg",
  "CORNEA_Conjunctival-papilloma.jpg",
  "CORNEA_Corneal-abrasion.jpg",
  "CORNEA_Corneal-hydrops.jpg",
  "CORNEA_Dermoid-cyst.jpg",
  "CORNEA_Descemetocele.jpg",
  "CORNEA_Disciform-keratitis.jpg",
  "CORNEA_Distichiasis.jpg",
  "CORNEA_Entropion.jpg",
  "CORNEA_Epithelial-downgrowth.jpg",
  "CORNEA_Fungal-keratitis.jpg",
  "CORNEA_Herpes-simplex-keratitis.jpg",
  "CORNEA_Hyphema.jpg",
  "CORNEA_Infectious-crystalline-keratopathy.jpg",
  "CORNEA_Iris-nevus.jpg",
  "CORNEA_Keratoconus.jpg",
  "CORNEA_Lipid-keratopathy.jpg",
  "CORNEA_Map-dot-fingerprint-dystrophy.jpg",
  "CORNEA_Microcornea.jpg",
  "CORNEA_Molluscum-contagiosum.jpg",
  "CORNEA_Papilloma.jpg",
  "CORNEA_Pellucid-marginal-degeneration.jpg",
  "CORNEA_Peripheral-ulcerative-keratitis-PUK.jpg",
  "CORNEA_Pinguecula.jpg",
  "CORNEA_Posterior-polymorphous-dystrophy-PPMD.jpg",
  "CORNEA_Pseudodendrite.jpg",
  "CORNEA_Pseudomonas-keratitis.jpg",
  "CORNEA_Pterygium.jpg",
  "CORNEA_Scleromalacia-perforans.jpg",
  "CORNEA_Subconjunctival-hemorrhage.jpg",
  "CORNEA_Superior-limbic-keratoconjunctivitis-SLK.jpg",
  "CORNEA_Vernal-keratoconjunctivitis.jpg",
  "CORNEA_Vogts-striae.jpg",
  "EXTERNAL DISEASE_Acanthamoeba-keratitis.jpg",
  "EXTERNAL DISEASE_Acute-Macular-Neuroretinopathy-AMN.jpg",
  "EXTERNAL DISEASE_Adenoviral-conjunctivitis.jpg",
  "EXTERNAL DISEASE_Alkali-chemical-burn.jpg",
  "EXTERNAL DISEASE_AlphaCor-keratoprosthesis.jpg",
  "EXTERNAL DISEASE_Angioid-Blepharokeratoconjunctivitis-of-childhood.jpg",
  "EXTERNAL DISEASE_Angioid-Streaks-and-Optic-Disc-Drusen-in-Pseudoxanthoma-Elasticum.jpg",
  "EXTERNAL DISEASE_Anterior-Scleritis.jpg",
  "EXTERNAL DISEASE_Bacterial-Conjunctivitis.jpg",
  "EXTERNAL DISEASE_Basal-cell-carcinoma.jpg",
  "EXTERNAL DISEASE_Blepharitis-and-meibomian-gland-dysfunction.jpg",
  "EXTERNAL DISEASE_Blepharitis.jpg",
  "EXTERNAL DISEASE_Boston-Keratoprosthesis-KPro-for-congenital-aniridia.jpg",
  "EXTERNAL DISEASE_Boston-Type-2-Keratoprosthesis-KPro.jpg",
  "EXTERNAL DISEASE_Branch-retinal-artery-occlusion-BRAO.jpg",
  "EXTERNAL DISEASE_Candida-growth-within-DSAEK-interface.jpg",
  "EXTERNAL DISEASE_Candida-infection-of-a-Boston-Type-I-Keratoprosthesis-KPro.jpg",
  "EXTERNAL DISEASE_Chalazia.jpg",
  "EXTERNAL DISEASE_Chemical-burn.jpg",
  "EXTERNAL DISEASE_Chlamydia-Trachomatis-Infection.jpg",
  "EXTERNAL DISEASE_Ciliary-Flush.jpg",
  "EXTERNAL DISEASE_Complex-choristoma-of-the-conjunctiva.jpg",
  "EXTERNAL DISEASE_Conductive-Keratoplasty.jpg",
  "EXTERNAL DISEASE_Conjunctival-Corneal-Invasive-Squamous-Cell-Carcinoma.jpg",
  "EXTERNAL DISEASE_Conjunctival-Inclusion-Cyst.jpg",
  "EXTERNAL DISEASE_Conjunctival-Nevus.jpg",
  "EXTERNAL DISEASE_Conjunctival-concretions.jpg",
  "EXTERNAL DISEASE_Conjunctival-epithelial-inclusion-cyst.jpg",
  "EXTERNAL DISEASE_Conjunctival-intraepithelial-neoplasia-CIN-with-full-thickness-dysplasia.jpg",
  "EXTERNAL DISEASE_Conjunctival-lymphangiectasis.jpg",
  "EXTERNAL DISEASE_Conjunctival-lymphoid-hyperplasia.jpg",
  "EXTERNAL DISEASE_Conjunctival-lymphoma.jpg",
  "EXTERNAL DISEASE_Conjunctival-oncocytoma.jpg",
  "EXTERNAL DISEASE_Conjunctival-papilloma-arising-from-the-caruncle.jpg",
  "EXTERNAL DISEASE_Conjunctival-papilloma.jpg",
  "EXTERNAL DISEASE_Conjunctival-squamous-papilloma.jpg",
  "EXTERNAL DISEASE_Conjunctival-varix.jpg",
  "EXTERNAL DISEASE_Corneal-Blood-Staining.jpg",
  "EXTERNAL DISEASE_Corneal-Hydrops.jpg",
  "EXTERNAL DISEASE_Corneal-abrasion.jpg",
  "EXTERNAL DISEASE_Corneal-and-lenticular-pigmentation-from-long-term-chlorpromazine-use.jpg",
  "EXTERNAL DISEASE_Corneal-melt-around-Boston-type-I-keratoprosthesis.jpg",
  "EXTERNAL DISEASE_CustomFlex-iris-prosthesis-and-penetrating-keratoplasty-PKP-for-acanthamoeba-keratitis.jpg",
  "EXTERNAL DISEASE_Distichiasis.jpg",
  "EXTERNAL DISEASE_Epidemic-Keratoconjunctivitis.jpg",
  "EXTERNAL DISEASE_Epidemic-adenoviral-keratoconjunctivitis.jpg",
  "EXTERNAL DISEASE_Erosive-vitreoretinopathy.jpg",
  "EXTERNAL DISEASE_Follicular-Conjunctivitis.jpg",
  "EXTERNAL DISEASE_Giant-Papillary-Conjunctivitis.jpg",
  "EXTERNAL DISEASE_Icterus-jaundice.jpg",
  "EXTERNAL DISEASE_Kaye-dots-in-a-penetrating-keratoplasty-graft.jpg",
  "EXTERNAL DISEASE_Khodadoust-Line-Corneal-Endothelial-Rejection.jpg",
  "EXTERNAL DISEASE_Lattice-corneal-dystrophy.jpg",
  "EXTERNAL DISEASE_Leukemic-pseudohypopyon.jpg",
  "EXTERNAL DISEASE_Limbal-Dermoid.jpg",
  "EXTERNAL DISEASE_Limbal-vernal-keratoconjunctivitis-VKC.jpg",
  "EXTERNAL DISEASE_Lissamine-green-staining-in-keratoconjunctivitis-sicca.jpg",
  "EXTERNAL DISEASE_Meibomian-Gland-Disease.jpg",
  "EXTERNAL DISEASE_Metallic-corneal-foreign-body.jpg",
  "EXTERNAL DISEASE_Opacification-of-Hydrophilic-Intraocular-Lens.jpg",
  "EXTERNAL DISEASE_Palpebral-vernal-keratoconjunctivitis-VKC.jpg",
  "EXTERNAL DISEASE_Peripheral-Ulcerative-Keratitis.jpg",
  "EXTERNAL DISEASE_Phlyctenular-Conjunctivitis.jpg",
  "EXTERNAL DISEASE_Pigmented-nevus-of-plica-semilunaris.jpg",
  "EXTERNAL DISEASE_Retisert-migration-into-the-anterior-chamber.jpg",
  "EXTERNAL DISEASE_Rosacea.jpg",
  "EXTERNAL DISEASE_Rose-Bengal-staining-in-Sjögrens-syndrome.jpg",
  "EXTERNAL DISEASE_Scleritis-2.jpg",
  "EXTERNAL DISEASE_Scleritis.jpg",
  "EXTERNAL DISEASE_Scleromalacia-in-Rheumatoid-Arthritis.jpg",
  "EXTERNAL DISEASE_Scleromalacia-perforans.jpg",
  "EXTERNAL DISEASE_Scleromalacia-with-transillumination-defect-in-the-setting-of-chronic-scleral-buckle-exposure.jpg",
  "EXTERNAL DISEASE_Scleromalacia.jpg",
  "EXTERNAL DISEASE_Squamous-papilloma.jpg",
  "EXTERNAL DISEASE_Stargardt-disease.jpg",
  "EXTERNAL DISEASE_Subconjunctival-Hematoma.jpg",
  "EXTERNAL DISEASE_Subconjunctival-Hemorrhage.jpg",
  "EXTERNAL DISEASE_Subconjunctival-foreign-bodies.jpg",
  "EXTERNAL DISEASE_Subconjunctival-metallic-foreign-body.jpg",
  "EXTERNAL DISEASE_Subconjunctival-prolapse-of-orbital-fat.jpg",
  "EXTERNAL DISEASE_Subconjunctival-silicone-oil.jpg",
  "EXTERNAL DISEASE_Subepithelial-corneal-haze-after-herpes-zoster-virus-HZV-keratitis.jpg",
  "EXTERNAL DISEASE_Superior-limbic-keratoconjunctivitis-SLK.jpg",
  "EXTERNAL DISEASE_Symblepharon.jpg",
  "EXTERNAL DISEASE_Tuberous-sclerosis.jpg",
  "EXTERNAL DISEASE_Viral-papilloma.jpg",
  "EXTERNAL DISEASE_Xanthelasma-Pathology.jpg",
  "EXTERNAL DISEASE_Xanthelasma.jpg",
  "GENETICS_Acute-Macular-Neuroretinopathy-AMN.jpg",
  "GENETICS_Angioid-Streaks-and-Optic-Disc-Drusen-in-Pseudoxanthoma-Elasticum.jpg",
  "GENETICS_Autosomal-dominant-neovascular-inflammatory-vitreoretinopathy-ADNIV.jpg",
  "GENETICS_Avellino-Dystrophy.jpg",
  "GENETICS_Batten-Disease.jpg",
  "GENETICS_Congenital-hypertrophy-of-the-retinal-pigmented-epithelium-CHRPE-in-a-\"bear-tracks\"-configuration.jpg",
  "GENETICS_Cuticular-Drusen.jpg",
  "GENETICS_Ectopia-lentis-in-Marfans-syndrome.jpg",
  "GENETICS_Familial-Exudative-Vitreoretinopathy-FEVR1.jpg",
  "GENETICS_Familial-Exudative-Vitreoretinopathy-FEVR3.jpg",
  "GENETICS_Familial-exudative-vitreoretinopathy-FEVR2.jpg",
  "GENETICS_Granular-corneal-dystrophy-type-1.jpg",
  "GENETICS_Granular-corneal-dystrophy.jpg",
  "GENETICS_Gyrate-atrophy.jpg",
  "GENETICS_LCHADD:-long-chain-3-hydroxyacyl-CoA-dehydrogenase-deficiency.jpg",
  "GENETICS_Lattice-corneal-dystrophy.jpg",
  "GENETICS_Leber-Congenital-Amaurosis,-RPE65-associated.jpg",
  "GENETICS_Leukemic-pseudohypopyon.jpg",
  "GENETICS_North-Carolina-macular-dystrophy.jpg",
  "GENETICS_Oculocutaneous-albinism.jpg",
  "GENETICS_Pseudoxanthoma-elasticum.jpg",
  "GENETICS_Stargardt-disease.jpg",
  "GENETICS_Tapetal-Sheen.jpg",
  "GENETICS_X-linked-retinoschisis-XLRS.jpg",
  "GLAUCOMA_Anterior-chamber-intraocular-lens-ACIOL-implant.jpg",
  "GLAUCOMA_Capsular-violation.jpg",
  "GLAUCOMA_Cataract-with-cortical-vacuoles.jpg",
  "GLAUCOMA_Glaukomflecken.jpg",
  "GLAUCOMA_Hyphema-following-aborted-iStent-procedure.jpg",
  "GLAUCOMA_Hyphema.jpg",
  "GLAUCOMA_Iris-bombe.jpg",
  "GLAUCOMA_Iris-nevus.jpg",
  "GLAUCOMA_Layered-intracapsular-hemorrhage-following-phacoemulsification-GATT.jpg",
  "GLAUCOMA_Microcornea.jpg",
  "GLAUCOMA_Opacification-of-Hydrophilic-Intraocular-Lens.jpg",
  "GLAUCOMA_Optic-nerve-head-drusen.jpg",
  "GLAUCOMA_Pseudoexfoliation-syndrome.jpg",
  "GLAUCOMA_Subluxated-posterior-chamber-intraocular-lens-implant.jpg",
  "INHERITED DISEASE_Choroideremia.jpg",
  "INHERITED DISEASE_Cystinosis.jpg",
  "INHERITED DISEASE_Familial-exudative-vitreoretinopathy-FEVR.jpg",
  "INHERITED DISEASE_Gyrate-atrophy.jpg",
  "INHERITED DISEASE_Leber-congenital-amaurosis-LCA.jpg",
  "INHERITED DISEASE_Oculocutaneous-albinism.jpg",
  "INHERITED DISEASE_Retinoblastoma.jpg",
  "IRIS_Capsular-violation.jpg",
  "IRIS_Cataract-with-cortical-vacuoles.jpg",
  "IRIS_Essential-iris-atrophy.jpg",
  "IRIS_Iris-bombe.jpg",
  "IRIS_Iris-coloboma.jpg",
  "IRIS_Iris-nevus.jpg",
  "IRIS_Layered-intracapsular-hemorrhage-following-phacoemulsification-GATT.jpg",
  "IRIS_Limbal-Dermoid.jpg",
  "IRIS_Melanocytoma.jpg",
  "IRIS_Opacification-of-Hydrophilic-Intraocular-Lens.jpg",
  "IRIS_Persistent-pupillary-membrane.jpg",
  "IRIS_Subluxated-posterior-chamber-intraocular-lens-implant.jpg",
  "IRIS_Unique-Electric-Cataract.jpg",
  "IRIS_Vitreous-strand-to-paracentesis-causing-subtle-peaked-pupil-early-in-case.jpg",
  "LENS_\"Y-suture\"-Cataract.jpg",
  "LENS_Anterior-chamber-intraocular-lens-ACIOL-implant.jpg",
  "LENS_Anterior-polar-cataract.jpg",
  "LENS_Anterior-subcapsular-cataract.jpg",
  "LENS_Calcific-Deposits-on-an-Intraocular-Lens.jpg",
  "LENS_Capsular-folds-secondary-to-posterior-capsule-opacification.jpg",
  "LENS_Capsular-violation.jpg",
  "LENS_Cataract-with-cortical-vacuoles.jpg",
  "LENS_Chlorpromazine-induced-cataract.jpg",
  "LENS_Circle-Contact-Lens.jpg",
  "LENS_Clear-crystalline-lens.jpg",
  "LENS_Combined-Anterior-Polar,-Posterior-Subcapsular-and-Cortical-Cataract.jpg",
  "LENS_Congenital-Cataract,-Sutural.jpg",
  "LENS_Congenital-lamellar-zonular-cataract-in-a-child.jpg",
  "LENS_Conjunctival-Prolapse-under-scleral-contact-lens.jpg",
  "LENS_Coppock-Cataract.jpg",
  "LENS_Corneal-and-lenticular-pigmentation-from-long-term-chlorpromazine-use.jpg",
  "LENS_Decentered-posterior-chamber-intraocular-lens.jpg",
  "LENS_Delayed-postoperative-fungal-endophthalmitis.jpg",
  "LENS_Dislocated-crystalline-lens.jpg",
  "LENS_Dislocated-intraocular-lens-implant.jpg",
  "LENS_Displaced-intraocular-lens.jpg",
  "LENS_Ectopia-lentis-in-Marfans-syndrome.jpg",
  "LENS_Epicapsular-stars-and-persistent-pupillary-membrane.jpg",
  "LENS_Glaukomflecken-and-iris-atrophy-after-acute-angle-closure-glaucoma.jpg",
  "LENS_Iris-coloboma.jpg",
  "LENS_Kayser-Fleischer-Ring-in-Wilsons-Disease.jpg",
  "LENS_Late-Capsular-Block-with-Posterior-Capsular-Fibrosis.jpg",
  "LENS_Layered-intracapsular-hemorrhage-following-phacoemulsification-GATT.jpg",
  "LENS_Lens-material-in-the-anterior-chamber-causing-chronic-uveitis.jpg",
  "LENS_Makeup-on-toric-soft-contact-lens.jpg",
  "LENS_McCannel-suture-scaffold-to-reconstruct-the-iris-plane.jpg",
  "LENS_Mittendorf-dot.jpg",
  "LENS_Morgagnian-cataract-with-absent-cortex.jpg",
  "LENS_Morgagnian-cataract.jpg",
  "LENS_Nocardia-farcinica-keratitis-in-a-contact-lens-wearer.jpg",
  "LENS_Nuclear-sclerotic-cataract.jpg",
  "LENS_Oil-droplet-cataract.jpg",
  "LENS_Ointment-in-anterior-chamber-after-cataract-surgery.jpg",
  "LENS_Persistent-Pupillary-Membrane-2.jpg",
  "LENS_Persistent-pupillary-membranes-1.jpg",
  "LENS_Phacomorphic-Angle-Closure-and-Anterior-Lens-Dislocation-due-to-Repeated-Blunt-Trauma.jpg",
  "LENS_Posterior-Polar-Cataract-with-Traumatic-Posterior-Capsule-Rupture.jpg",
  "LENS_Posterior-Polar-Cataract.jpg",
  "LENS_Posterior-capsular-opacity-PCO-following-cataract-surgery.jpg",
  "LENS_Posterior-subcapsular-cataract--retroillumination.jpg",
  "LENS_Posterior-subcapsular-cataract.jpg",
  "LENS_Pseudoexfoliation-syndrome.jpg",
  "LENS_Pseudoexfoliation-zonular-dehiscence.jpg",
  "LENS_Retained-Lens-Fragment.jpg",
  "LENS_Siderosis-bulbi.jpg",
  "LENS_Silicone-oil-droplet-on-intraocular-lens-IOL.jpg",
  "LENS_Soft-Contact-Lens.jpg",
  "LENS_Subluxated-posterior-chamber-intraocular-lens-implant.jpg",
  "LENS_Suture-iris-reconstruction-using-McCannel-suture-technique.jpg",
  "LENS_Temporal-iris-and-lens-coloboma-associated-with-cataract.jpg",
  "LENS_Toric-Soft-Contact-Lens.jpg",
  "LENS_Traumatic-aniridia-and-cataract.jpg",
  "LENS_Traumatic-cataract-with-iridodialysis-and-lens-coloboma.jpg",
  "LENS_Traumatic-rosette-cataract.jpg",
  "LENS_Typical-Corneal-Rigid-Gas-Permeable-RGP-Contact-Lens.jpg",
  "LENS_Unique-Electric-Cataract.jpg",
  "LENS_Visian-Implantable-Collamer-Lens-ICL-implant.jpg",
  "LENS_Visualization-of-posterior-persistent-fetal-vasculature-following-lens-subluxation.jpg",
  "LENS_White-cataract-from-trauma.jpg",
  "NEURO-OP_6th-nerve-palsy,-left-eye.jpg",
  "NEURO-OP_Aberrent-Regeneration,-3rd-Nerve-Palsy.jpg",
  "NEURO-OP_Anomalous-appearing-optic-nerves-in-both-eyes.jpg",
  "NEURO-OP_Apraclonidine-Drop-Testing-for-Horner-Syndrome.jpg",
  "NEURO-OP_Autosomal-Recessive-Best-Disease.jpg",
  "NEURO-OP_Bartonella-Neuroretinitis.jpg",
  "NEURO-OP_Bilateral-4th-Nerve-Palsy.jpg",
  "NEURO-OP_Bilateral-Cranial-Nerve-VI-Abducens-Nerve-Palsies-Secondary-to-Retroclival-Hematoma.jpg",
  "NEURO-OP_Bilateral-Cranial-Nerve-VI-Palsies-Secondary-to-Arachnoid-Cyst.jpg",
  "NEURO-OP_Bilateral-occipital-infarcts-stroke.jpg",
  "NEURO-OP_Bow-tie-band-atrophy-secondary-to-compressive-optic-neuropathy.jpg",
  "NEURO-OP_Cavernous-Sinus-Syndrome.jpg",
  "NEURO-OP_Cerebral-venous-sinus-thrombosis-causing-intracranial-hypertension.jpg",
  "NEURO-OP_Congenital-tilting-of-the-optic-nerve-with-situs-inversus.jpg",
  "NEURO-OP_Cranial-Nerve-IV-Trochlear-Nerve-Palsy.jpg",
  "NEURO-OP_Cranial-Nerve-VI-Abducens-Nerve-Palsy-Secondary-to-Schwannoma.jpg",
  "NEURO-OP_Eight-and-a-Half-Syndrome.jpg",
  "NEURO-OP_Exophthalmos-secondary-to-a-carotid-cavernous-fistula.jpg",
  "NEURO-OP_Facial-Colliculus-Syndrome.jpg",
  "NEURO-OP_Horners-Syndrome.jpg",
  "NEURO-OP_Idiopathic-Intracranial-Hypertension-IIH,-Pseudotumor-Cerebri.jpg",
  "NEURO-OP_Internuclear-ophthalmoplegia-INO.jpg",
  "NEURO-OP_Kearns-Sayre-syndrome.jpg",
  "NEURO-OP_Left-homonymous-hemianopsia,-occipital-stroke.jpg",
  "NEURO-OP_Long-Ciliary-Nerve.jpg",
  "NEURO-OP_Megalo-optic-disk.jpg",
  "NEURO-OP_Morning-Glory-Disc-Anomaly-with-Peripapillary-Staphyloma.jpg",
  "NEURO-OP_Myasthenia-Gravis-edrophonium-test.jpg",
  "NEURO-OP_Neurosarcoidosis.jpg",
  "NEURO-OP_Non-arteritic-anterior-ischemic-optic-neuropathy-NAION.jpg",
  "NEURO-OP_Olfactory-groove-meningioma-in-a-pregnant-female.jpg",
  "NEURO-OP_Optic-Disc-Drusen-with-asteroid-hyalosis.jpg",
  "NEURO-OP_Optic-Disc-Drusen.jpg",
  "NEURO-OP_Optic-Nerve-Coloboma-with-Optic-Pits.jpg",
  "NEURO-OP_Optic-Nerve-Head-Drusen.jpg",
  "NEURO-OP_Optic-nerve-coloboma-with-staphyloma.jpg",
  "NEURO-OP_Optic-nerve-drusen.jpg",
  "NEURO-OP_Optic-nerve-hypoplasia.jpg",
  "NEURO-OP_Optic-nerve-pit-maculopathy.jpg",
  "NEURO-OP_Optic-nerve-sheath-meningioma.jpg",
  "NEURO-OP_Optociliary-shunt-vessels.jpg",
  "NEURO-OP_Papilledema-secondary-to-meningitis.jpg",
  "NEURO-OP_Papilledema.jpg",
  "NEURO-OP_Physiologic-anisocoria.jpg",
  "NEURO-OP_Pituitary-adenoma.jpg",
  "NEURO-OP_Pseudo-Foster-Kennedy-syndrome.jpg",
  "NEURO-OP_Spiraling-Isopters-in-Non-Organic-Vision-Loss.jpg",
  "NEURO-OP_Superior-segmental-optic-nerve-hypoplasia.jpg",
  "NEURO-OP_Tadpole-Pupil.jpg",
  "OCULOPLASTICS_Ankyloblepharon.jpg",
  "OCULOPLASTICS_Apocrine-hidrocystoma.jpg",
  "OCULOPLASTICS_Basal-cell-carcinoma.jpg",
  "OCULOPLASTICS_Blepharitis.jpg",
  "OCULOPLASTICS_Conjunctival-lymphoma.jpg",
  "OCULOPLASTICS_Conjunctival-papilloma.jpg",
  "OCULOPLASTICS_Dermoid-cyst.jpg",
  "OCULOPLASTICS_Distichiasis.jpg",
  "OCULOPLASTICS_Entropion.jpg",
  "OCULOPLASTICS_Keratoacanthoma.jpg",
  "OCULOPLASTICS_Madarosis.jpg",
  "OCULOPLASTICS_Merkel-cell-carcinoma.jpg",
  "OCULOPLASTICS_Molluscum-contagiosum.jpg",
  "OCULOPLASTICS_Papilloma.jpg",
  "OCULOPLASTICS_Pyogenic-granuloma.jpg",
  "OCULOPLASTICS_Seborrheic-keratosis.jpg",
  "PATHOLOGY_Band-keratopathy.jpg",
  "PATHOLOGY_Basal-cell-carcinoma-nodular-type.jpg",
  "PATHOLOGY_Bergmeister-Papilla.jpg",
  "PATHOLOGY_Cavernous-hemangioma.jpg",
  "PATHOLOGY_Chalazion.jpg",
  "PATHOLOGY_Choroidal-malignant-melanoma-in-a-\"collar-button\"-configuration.jpg",
  "PATHOLOGY_Choroidal-melanoma,-histology.jpg",
  "PATHOLOGY_Dacryolith-due-to-Actinomyces-israelii.jpg",
  "PATHOLOGY_EyeRounds-Online-Atlas-of-Ophthalmology.jpg",
  "PATHOLOGY_Giant-cell-arteritis.jpg",
  "PATHOLOGY_Pleomorphic-adenoma.jpg",
  "PATHOLOGY_Plexiform-neurofibroma.jpg",
  "PATHOLOGY_Retinoblastoma.jpg",
  "PATHOLOGY_Seborrheic-keratosis.jpg",
  "RETINA_Acute-Macular-Neuroretinopathy-AMN.jpg",
  "RETINA_Age-related-macular-degeneration-AMD.jpg",
  "RETINA_Angioid-streaks.jpg",
  "RETINA_Asteroid-hyalosis.jpg",
  "RETINA_Bear-tracks.jpg",
  "RETINA_Birdshot-chorioretinopathy.jpg",
  "RETINA_Branch-retinal-artery-occlusion-BRAO.jpg",
  "RETINA_Central-retinal-artery-occlusion-CRAO.jpg",
  "RETINA_Central-retinal-vein-occlusion-CRVO.jpg",
  "RETINA_Choroideremia.jpg",
  "RETINA_Cytomegalovirus-CMV-retinitis.jpg",
  "RETINA_Dislocated-intraocular-lens.jpg",
  "RETINA_Epiretinal-membrane-ERM.jpg",
  "RETINA_Familial-exudative-vitreoretinopathy-FEVR.jpg",
  "RETINA_Gyrate-atrophy.jpg",
  "RETINA_Hollenhorst-plaque.jpg",
  "RETINA_Idiopathic-intracranial-hypertension-IIH.jpg",
  "RETINA_Lattice-degeneration.jpg",
  "RETINA_Leber-congenital-amaurosis-LCA.jpg",
  "RETINA_Melanocytoma.jpg",
  "RETINA_North-Carolina-macular-dystrophy.jpg",
  "RETINA_Optic-nerve-head-drusen.jpg",
  "RETINA_Optic-nerve-pit.jpg",
  "RETINA_Papilledema.jpg",
  "RETINA_Persistent-fetal-vasculature-PFV.jpg",
  "RETINA_Retinoblastoma.jpg",
  "RETINA_Valsalva-retinopathy.jpg",
  "TRAUMA_Adherent-leukoma-and-epithelial-inclusion-cyst-after-penetrating-trauma.jpg",
  "TRAUMA_Alkali-chemical-burn.jpg",
  "TRAUMA_Blowout-fracture,-upgaze-restriction.jpg",
  "TRAUMA_Bullous-Sub-conjunctival-hemorrhage,-early.jpg",
  "TRAUMA_Bullous-subconjunctival-hemorrhage-from-orbital-roof-fracture.jpg",
  "TRAUMA_Choroidal-Rupture.jpg",
  "TRAUMA_Combined-Hamartoma-of-the-Retina-and-RPE,-Peri-Papillary.jpg",
  "TRAUMA_Commotio-retinae.jpg",
  "TRAUMA_Conjunctival-laceration.jpg",
  "TRAUMA_Corneal-abrasion.jpg",
  "TRAUMA_Descemets-membrane-rupture-secondary-to-forceps-injury.jpg",
  "TRAUMA_Ferrous-foreign-body:-Rust-ring.jpg",
  "TRAUMA_Iridodialysis-and-traumatic-cataract-after-firecracker-injury.jpg",
  "TRAUMA_Iridodialysis.jpg",
  "TRAUMA_Large-Intraocular-Foreign-Body.jpg",
  "TRAUMA_Lid-Margin-laceration.jpg",
  "TRAUMA_Lid-laceration---full-thickness.jpg",
  "TRAUMA_Lipid-Keratopathy,-post-trauma.jpg",
  "TRAUMA_Macular-hole,-commotio-retinae,-and-choroidal-rupture-after-blunt-eye-injury.jpg",
  "TRAUMA_Medial-wall-and-orbital-floor-blowout-fractures,-left.jpg",
  "TRAUMA_Metallic-corneal-foreign-body.jpg",
  "TRAUMA_Morcher-intraocular-lens-and-penetrating-keratoplasty-PKP-for-traumatic-aniridia.jpg",
  "TRAUMA_Non-accidental-trauma-Bilateral-Retinal-Hemorrhages.jpg",
  "TRAUMA_Orbital-Foreign-Body.jpg",
  "TRAUMA_Orbital-fractures-and-trauma.jpg",
  "TRAUMA_Peaked-pupil-from-open-globe.jpg",
  "TRAUMA_Penetrating-ocular-trauma.jpg",
  "TRAUMA_Scalding-burn.jpg",
  "TRAUMA_Sclopetaria.jpg",
  "TRAUMA_Siderosis-bulbi.jpg",
  "TRAUMA_Subconjunctival-Hematoma.jpg",
  "TRAUMA_Subconjunctival-Hemorrhage.jpg",
  "TRAUMA_Subconjunctival-metallic-foreign-body.jpg",
  "TRAUMA_Superglue-in-the-eye.jpg",
  "TRAUMA_Traumatic-aniridia-and-cataract.jpg",
  "TRAUMA_Traumatic-cataract-with-iridodialysis-and-lens-coloboma.jpg",
  "TRAUMA_Traumatic-endophthalmitis.jpg",
  "TRAUMA_Traumatic-endothelial-pigment-deposition.jpg",
  "TRAUMA_Traumatic-hyphema.jpg",
  "TRAUMA_Traumatic-iris-sphincter-tears.jpg",
  "TRAUMA_Traumatic-rosette-cataract.jpg",
  "TRAUMA_White-cataract-from-trauma.jpg",
  "TRAUMA_Zygomatic-maxillary-complex-ZMC-tripod-fracture.jpg",
  "UVEITIS_Central-posterior-synechiae-CPS-in-the-setting-of-tubulointerstitial-nephritis-and-uveitis-syndrome-TINU.jpg",
  "UVEITIS_Keratic-precipitates-KP-in-juvenile-idiopathic-arthritis-JIA.jpg",
  "UVEITIS_Lens-material-in-the-anterior-chamber-causing-chronic-uveitis.jpg",
  "UVEITIS_Leukemic-pseudohypopyon.jpg",
  "UVEITIS_Multiple-evanescent-white-dot-syndrome-MEWDS.jpg",
  "UVEITIS_Mutton-Fat-Keratic-Precipitates-KP.jpg",
  "UVEITIS_Punctate-inner-choroiditis-PIC.jpg",
  "UVEITIS_Scleromalacia-in-Rheumatoid-Arthritis.jpg"
];
